//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnAFile.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurnAFile.Windows.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate license.
        /// </summary>
        public static string AboutActivateLicense {
            get {
                return ResourceManager.GetString("AboutActivateLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        public static string AboutBuyLicense {
            get {
                return ResourceManager.GetString("AboutBuyLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About TurnAFile.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple and local media conversion.
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TurnAFile.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio.
        /// </summary>
        public static string AudioLabel {
            get {
                return ResourceManager.GetString("AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        public static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear all.
        /// </summary>
        public static string ContextMenuClearAll {
            get {
                return ResourceManager.GetString("ContextMenuClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert to.
        /// </summary>
        public static string ContextMenuConvertTo {
            get {
                return ResourceManager.GetString("ContextMenuConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extract text (OCR).
        /// </summary>
        public static string ContextMenuExtractOCR {
            get {
                return ResourceManager.GetString("ContextMenuExtractOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quality.
        /// </summary>
        public static string ContextMenuQuality {
            get {
                return ResourceManager.GetString("ContextMenuQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High Quality.
        /// </summary>
        public static string ContextMenuQualityHigh {
            get {
                return ResourceManager.GetString("ContextMenuQualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low Quality.
        /// </summary>
        public static string ContextMenuQualityLow {
            get {
                return ResourceManager.GetString("ContextMenuQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Quality.
        /// </summary>
        public static string ContextMenuQualityMedium {
            get {
                return ResourceManager.GetString("ContextMenuQualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove from list.
        /// </summary>
        public static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as DOCX.
        /// </summary>
        public static string ContextMenuSaveAsDOCX {
            get {
                return ResourceManager.GetString("ContextMenuSaveAsDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as TXT.
        /// </summary>
        public static string ContextMenuSaveAsTXT {
            get {
                return ResourceManager.GetString("ContextMenuSaveAsTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as XLSX.
        /// </summary>
        public static string ContextMenuSaveAsXLSX {
            get {
                return ResourceManager.GetString("ContextMenuSaveAsXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Conversion_cancelButton {
            get {
                return ResourceManager.GetString("Conversion_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progress.
        /// </summary>
        public static string Conversion_progressLabel {
            get {
                return ResourceManager.GetString("Conversion_progressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversion cancelled.
        /// </summary>
        public static string ConversionCancelled {
            get {
                return ResourceManager.GetString("ConversionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversion completed.
        /// </summary>
        public static string ConversionCompleted {
            get {
                return ResourceManager.GetString("ConversionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversion error.
        /// </summary>
        public static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A conversion is already in progress. Please wait..
        /// </summary>
        public static string ConversionInProgress {
            get {
                return ResourceManager.GetString("ConversionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Converting files....
        /// </summary>
        public static string ConversionProgress_Title {
            get {
                return ResourceManager.GetString("ConversionProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert.
        /// </summary>
        public static string ConvertButton {
            get {
                return ResourceManager.GetString("ConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        public static string DataLabel {
            get {
                return ResourceManager.GetString("DataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doc.
        /// </summary>
        public static string DocumentLabel {
            get {
                return ResourceManager.GetString("DocumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drag files here.
        /// </summary>
        public static string DragFilesMessage {
            get {
                return ResourceManager.GetString("DragFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error converting {0}.
        /// </summary>
        public static string ErrorConvertingFile {
            get {
                return ResourceManager.GetString("ErrorConvertingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FFmpeg not found.
        /// </summary>
        public static string FFmpegNotFound {
            get {
                return ResourceManager.GetString("FFmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported file type: {0}.
        /// </summary>
        public static string FileTypeNotSupported {
            get {
                return ResourceManager.GetString("FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        public static string FormatHeader {
            get {
                return ResourceManager.GetString("FormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have {0} files.
        ///
        ///The free version processes up to {1} per batch.
        ///
        ///{2} files will be processed. The remaining {3} will NOT be converted.
        ///
        ///Do you want to continue?.
        /// </summary>
        public static string FreeVersionBatchLimit {
            get {
                return ResourceManager.GetString("FreeVersionBatchLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free version limit.
        /// </summary>
        public static string FreeVersionLimitTitle {
            get {
                return ResourceManager.GetString("FreeVersionLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        public static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ??.
        /// </summary>
        public static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Français.
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deutsch.
        /// </summary>
        public static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ???.
        /// </summary>
        public static string LanguageJapanese {
            get {
                return ResourceManager.GetString("LanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate.
        /// </summary>
        public static string LicenseActivate {
            get {
                return ResourceManager.GetString("LicenseActivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Full name.
        /// </summary>
        public static string LicenseFullName {
            get {
                return ResourceManager.GetString("LicenseFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Email address.
        /// </summary>
        public static string LicenseEmailLabel {
            get {
                return ResourceManager.GetString("LicenseEmailLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a License key.
        /// </summary>
        public static string LicenseKeyLabel {
            get {
                return ResourceManager.GetString("LicenseKeyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Option 1: Load license file.
        /// </summary>
        public static string LicenseOption1 {
            get {
                return ResourceManager.GetString("LicenseOption1", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Option 2: Enter data manually.
        /// </summary>
        public static string LicenseOption2 {
            get {
                return ResourceManager.GetString("LicenseOption2", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ?? Load .key file.
        /// </summary>
        public static string LicenseLoadFile {
            get {
                return ResourceManager.GetString("LicenseLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate TurnAFile License.
        /// </summary>
        public static string LicenseActivationTitle {
            get {
                return ResourceManager.GetString("LicenseActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string LicenseEmail {
            get {
                return ResourceManager.GetString("LicenseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License file.
        /// </summary>
        public static string LicenseFile {
            get {
                return ResourceManager.GetString("LicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select license file.
        /// </summary>
        public static string LicenseSelectFile {
            get {
                return ResourceManager.GetString("LicenseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No files selected.
        /// </summary>
        public static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (same location as original).
        /// </summary>
        public static string OutputFolderDefault {
            get {
                return ResourceManager.GetString("OutputFolderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High.
        /// </summary>
        public static string QualityHigh {
            get {
                return ResourceManager.GetString("QualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        public static string QualityLow {
            get {
                return ResourceManager.GetString("QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        public static string QualityMedium {
            get {
                return ResourceManager.GetString("QualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate.
        /// </summary>
        public static string ReminderActivate {
            get {
                return ResourceManager.GetString("ReminderActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Later.
        /// </summary>
        public static string ReminderLater {
            get {
                return ResourceManager.GetString("ReminderLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your trial period has expired. Activate your license to continue using all features..
        /// </summary>
        public static string ReminderMessage {
            get {
                return ResourceManager.GetString("ReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate your license.
        /// </summary>
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected files.
        /// </summary>
        public static string SelectedFilesTitle {
            get {
                return ResourceManager.GetString("SelectedFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select files.
        /// </summary>
        public static string SelectFilesButton {
            get {
                return ResourceManager.GetString("SelectFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select at least one file to convert..
        /// </summary>
        public static string SelectFilesMessage {
            get {
                return ResourceManager.GetString("SelectFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select output folder.
        /// </summary>
        public static string SelectOutputFolderTitle {
            get {
                return ResourceManager.GetString("SelectOutputFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to TurnAFile.
        /// </summary>
        public static string ShellMenuAddEntry {
            get {
                return ResourceManager.GetString("ShellMenuAddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TurnAFile.
        /// </summary>
        public static string ShellMenuAppName {
            get {
                return ResourceManager.GetString("ShellMenuAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert to {0}.
        /// </summary>
        public static string ShellMenuConvertTo {
            get {
                return ResourceManager.GetString("ShellMenuConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert with TurnAFile.
        /// </summary>
        public static string ShellMenuConvertWith {
            get {
                return ResourceManager.GetString("ShellMenuConvertWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extract text (OCR).
        /// </summary>
        public static string ShellMenuExtractOCR {
            get {
                return ResourceManager.GetString("ShellMenuExtractOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High Quality.
        /// </summary>
        public static string ShellMenuQualityHigh {
            get {
                return ResourceManager.GetString("ShellMenuQualityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low Quality.
        /// </summary>
        public static string ShellMenuQualityLow {
            get {
                return ResourceManager.GetString("ShellMenuQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Quality.
        /// </summary>
        public static string ShellMenuQualityMedium {
            get {
                return ResourceManager.GetString("ShellMenuQualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as DOCX.
        /// </summary>
        public static string ShellMenuSaveAsDOCX {
            get {
                return ResourceManager.GetString("ShellMenuSaveAsDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as TXT.
        /// </summary>
        public static string ShellMenuSaveAsTXT {
            get {
                return ResourceManager.GetString("ShellMenuSaveAsTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as XLSX.
        /// </summary>
        public static string ShellMenuSaveAsXLSX {
            get {
                return ResourceManager.GetString("ShellMenuSaveAsXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle light/dark theme.
        /// </summary>
        public static string ThemeToggleTooltip {
            get {
                return ResourceManager.GetString("ThemeToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        public static string VideoLabel {
            get {
                return ResourceManager.GetString("VideoLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Status: Licensed.
        /// </summary>
        public static string LicenseStatusLicensed {
            get {
                return ResourceManager.GetString("LicenseStatusLicensed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Status: Free.
        /// </summary>
        public static string LicenseStatusFree {
            get {
                return ResourceManager.GetString("LicenseStatusFree", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Limit: No file limit.
        /// </summary>
        public static string LicenseNoFileLimit {
            get {
                return ResourceManager.GetString("LicenseNoFileLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Licensed to: {0}.
        /// </summary>
        public static string LicensedTo {
            get {
                return ResourceManager.GetString("LicensedTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Limit: 10 files per batch | {0} trial days remaining.
        /// </summary>
        public static string LicenseBatchLimitWithDays {
            get {
                return ResourceManager.GetString("LicenseBatchLimitWithDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Limit: 10 files per batch | Free mode.
        /// </summary>
        public static string LicenseBatchLimitFreeMode {
            get {
                return ResourceManager.GetString("LicenseBatchLimitFreeMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Processing file {0} of {1}.
        /// </summary>
        public static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Time remaining: calculating....
        /// </summary>
        public static string TimeRemainingCalculating {
            get {
                return ResourceManager.GetString("TimeRemainingCalculating", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Time remaining: {0}.
        /// </summary>
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Conversion completed!.
        /// </summary>
        public static string ConversionCompletedStatus {
            get {
                return ResourceManager.GetString("ConversionCompletedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error: {0}.
        /// </summary>
        public static string ConversionErrorStatus {
            get {
                return ResourceManager.GetString("ConversionErrorStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cancelling....
        /// </summary>
        public static string CancellingStatus {
            get {
                return ResourceManager.GetString("CancellingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Completed.
        /// </summary>
        public static string ButtonCompleted {
            get {
                return ResourceManager.GetString("ButtonCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ButtonError {
            get {
                return ResourceManager.GetString("ButtonError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Convert to {0}.
        /// </summary>
        public static string ConvertToFormat {
            get {
                return ResourceManager.GetString("ConvertToFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a High.
        /// </summary>
        public static string QualityAlta {
            get {
                return ResourceManager.GetString("QualityAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        public static string QualityMedia {
            get {
                return ResourceManager.GetString("QualityMedia", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        public static string QualityBaja {
            get {
                return ResourceManager.GetString("QualityBaja", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Select output folder.
        /// </summary>
        public static string SelectOutputFolderDialog {
            get {
                return ResourceManager.GetString("SelectOutputFolderDialog", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Could not open browser: {0}.
        /// </summary>
        public static string ErrorOpeningBrowser {
            get {
                return ResourceManager.GetString("ErrorOpeningBrowser", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The license file is not valid..
        /// </summary>
        public static string InvalidLicenseFile {
            get {
                return ResourceManager.GetString("InvalidLicenseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error reading file: {0}.
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a The email address is not valid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error reinstalling context menu: {0}.
        /// </summary>
        public static string ErrorReinstallingMenu {
            get {
                return ResourceManager.GetString("ErrorReinstallingMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a File not found: {0}.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a FFmpeg not found. Please reinstall the application..
        /// </summary>
        public static string FFmpegNotFoundMessage {
            get {
                return ResourceManager.GetString("FFmpegNotFoundMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Could not open link: {0}.
        /// </summary>
        public static string CouldNotOpenLink {
            get {
                return ResourceManager.GetString("CouldNotOpenLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a License activated successfully..
        /// </summary>
        public static string LicenseActivated {
            get {
                return ResourceManager.GetString("LicenseActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Could not convert the file..
        /// </summary>
        public static string CouldNotConvertFile {
            get {
                return ResourceManager.GetString("CouldNotConvertFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Conversion cancelled..
        /// </summary>
        public static string ConversionCancelledMsg {
            get {
                return ResourceManager.GetString("ConversionCancelledMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Developed by.
        /// </summary>
        public static string AboutDevelopedBy {
            get {
                return ResourceManager.GetString("AboutDevelopedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Format and quality icons.
        /// </summary>
        public static string AboutFormatIcons {
            get {
                return ResourceManager.GetString("AboutFormatIcons", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a dash separator.
        /// </summary>
        public static string AboutIconsDash {
            get {
                return ResourceManager.GetString("AboutIconsDash", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Media conversion.
        /// </summary>
        public static string AboutFFmpegDesc {
            get {
                return ResourceManager.GetString("AboutFFmpegDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ClosedXML.
        /// </summary>
        public static string AboutClosedXML {
            get {
                return ResourceManager.GetString("AboutClosedXML", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Excel file processing.
        /// </summary>
        public static string AboutClosedXMLDesc {
            get {
                return ResourceManager.GetString("AboutClosedXMLDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PDFsharp.
        /// </summary>
        public static string AboutPDFsharp {
            get {
                return ResourceManager.GetString("AboutPDFsharp", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PDF document generation.
        /// </summary>
        public static string AboutPDFsharpDesc {
            get {
                return ResourceManager.GetString("AboutPDFsharpDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Open XML SDK.
        /// </summary>
        public static string AboutOpenXML {
            get {
                return ResourceManager.GetString("AboutOpenXML", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Document format conversion.
        /// </summary>
        public static string AboutOpenXMLDesc {
            get {
                return ResourceManager.GetString("AboutOpenXMLDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a QuestPDF.
        /// </summary>
        public static string AboutQuestPDF {
            get {
                return ResourceManager.GetString("AboutQuestPDF", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PDF document generation.
        /// </summary>
        public static string AboutQuestPDFDesc {
            get {
                return ResourceManager.GetString("AboutQuestPDFDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Special thanks.
        /// </summary>
        public static string AboutSpecialThanks {
            get {
                return ResourceManager.GetString("AboutSpecialThanks", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Special thanks message.
        /// </summary>
        public static string AboutSpecialThanksMessage {
            get {
                return ResourceManager.GetString("AboutSpecialThanksMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Technologies used.
        /// </summary>
        public static string AboutTechnologiesUsed {
            get {
                return ResourceManager.GetString("AboutTechnologiesUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tech list.
        /// </summary>
        public static string AboutTechList {
            get {
                return ResourceManager.GetString("AboutTechList", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a License.
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a License info.
        /// </summary>
        public static string AboutLicenseInfo {
            get {
                return ResourceManager.GetString("AboutLicenseInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a View terms.
        /// </summary>
        public static string AboutViewTerms {
            get {
                return ResourceManager.GetString("AboutViewTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External Tool Licenses.
        /// </summary>
        public static string ExternalLicensesTitle {
            get {
                return ResourceManager.GetString("ExternalLicensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Third-Party Component Licenses.
        /// </summary>
        public static string ExternalLicensesHeader {
            get {
                return ResourceManager.GetString("ExternalLicensesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a component from the dropdown.
        /// </summary>
        public static string ExternalLicensesDescription {
            get {
                return ResourceManager.GetString("ExternalLicensesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Component:.
        /// </summary>
        public static string SelectComponent {
            get {
                return ResourceManager.GetString("SelectComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Folder.
        /// </summary>
        public static string OpenFolderButton {
            get {
                return ResourceManager.GetString("OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No external license files found..
        /// </summary>
        public static string NoExternalLicensesFound {
            get {
                return ResourceManager.GetString("NoExternalLicensesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a component first..
        /// </summary>
        public static string NoComponentSelected {
            get {
                return ResourceManager.GetString("NoComponentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View External Licenses.
        /// </summary>
        public static string ViewExternalLicensesButton {
            get {
                return ResourceManager.GetString("ViewExternalLicensesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TurnAFile context menu reinstalled successfully..
        /// </summary>
        public static string LicenseReinstallSuccess {
            get {
                return ResourceManager.GetString("LicenseReinstallSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a OCR conversion failed.
        /// </summary>
        public static string OCRConversionFailed {
            get {
                return ResourceManager.GetString("OCRConversionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Pandoc not found at: {0}.
        /// </summary>
        public static string PandocNotFoundMessage {
            get {
                return ResourceManager.GetString("PandocNotFoundMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Document conversion failed.
        /// </summary>
        public static string DocumentConversionFailed {
            get {
                return ResourceManager.GetString("DocumentConversionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported data conversion: {0} to {1}.
        /// </summary>
        public static string UnsupportedDataConversion {
            get {
                return ResourceManager.GetString("UnsupportedDataConversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Data conversion failed.
        /// </summary>
        public static string DataConversionFailed {
            get {
                return ResourceManager.GetString("DataConversionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Could not generate PDF from image.
        /// </summary>
        public static string CouldNotGeneratePDF {
            get {
                return ResourceManager.GetString("CouldNotGeneratePDF", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error generating PDF.
        /// </summary>
        public static string ErrorGeneratingPDF {
            get {
                return ResourceManager.GetString("ErrorGeneratingPDF", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PDF generation error.
        /// </summary>
        public static string PDFGeneratedError {
            get {
                return ResourceManager.GetString("PDFGeneratedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Conversion cancelled.
        /// </summary>
        public static string ConversionCancelledStatus {
            get {
                return ResourceManager.GetString("ConversionCancelledStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a General error.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
    }
}
